### ISSUE TITLE
Chapter10_Mask_R_CNN_Image_Segmentation_Demo: ERROR: Not connected to a TPU runtime

### ISSUE THREAD

**Issue by mikechen66** [PacktPublishing/Mastering-Computer-Vision-with-TensorFlow-2.0#10]
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-5-b82bc0a42032> in <module>
      4   import pprint
      5 
----> 6   assert 'COLAB_TPU_ADDR' in os.environ, 'ERROR: Not connected to a TPU runtime; please see the first cell in this notebook for instructions!'
      7   TPU_ADDRESS = 'grpc://' + os.environ['COLAB_TPU_ADDR']
      8   print('TPU address is', TPU_ADDRESS)

AssertionError: ERROR: Not connected to a TPU runtime; please see the first cell in this notebook for instructions!

**Comment by KrishkarPackt** [comment]
Hello, Did you connect to TPU as instructed in the book
On the main menu, click Runtime and select Change runtime type. Set "TPU" as the hardware accelerator.
Cloning into 'tpu'...
remote: Enumerating objects: 9643, done.
remote: Total 9643 (delta 0), reused 0 (delta 0), pack-reused 9643
Receiving objects: 100% (9643/9643), 24.20 MiB | 28.07 MiB/s, done.
Resolving deltas: 100% (6915/6915), done.

**Comment by KrishkarPackt** [comment]
I gave example above - I am able to connect to TPU

**Comment by mikechen66** [comment]
Ok, thanks for your feedback. I will try it according to your confirmation. 

Thank a lot.

**Comment by deepesh-packt** [comment]
Please reopen if the issue still persists.
