### ISSUE TITLE
Renaming image files in chapter 10

### ISSUE THREAD

**Issue by linchiyu** [PacktPublishing/Mastering-Computer-Vision-with-TensorFlow-2.0#2]
Hi, i'm testing the Training a custom object detector using TensorFlow and Google Colab in Chapter 10. And i'm wondering if is it really necessary to rename the image files in the training and test files.
I'm reffering at the 6th step at "Collecting and formatting images as .jpg files", where images need to renamed to classname_00x.jpg.

Is that step necessary?

**Comment by KrishkarPackt** [comment]
I prefer to rename images as best practice - I have used batch rename option in Linux Files or MAC finder.  You do not have to manually rename it - you can select all files - right click and choose rename rules.  Two reasons for renaming: 
1) I remember I had some error of inconsistency when I convert to tfRecord - do not recollect exact reason.  So I prefer renaming to be 100% sure later on I will not run into problem
2) each jpg image has corresponding xml file and they come next to each other as shown in step 8 of separating the file by train and test folders.  With rename you can keep track of the file easily -without renaming there may be a danger of a jpg image associated with a wrong xml file - and you will have no way to find that error later on when the model is created.

I hope this helps.

**Comment by KrishkarPackt** [comment]
There is a third reason
3) suppose you developed your initial model with 1000 images and now gather another 500 images to update your model.  If you rename all 1000 images - your last image number will end with  _1000 and the new images will start with _1001.  So there will be no image overwritten.  Without renaming there is a danger that two images names are same and may get overwritten - resulting in wrong xml file corresponding to a jpg file.

**Comment by linchiyu** [comment]
Got it, 
Thank you
