### ISSUE TITLE
Chapter4_classification_visualization_custom_model&VGG: ResourceExhaustedError: OOM when allocating tensor with shape[173056,4096]

### ISSUE THREAD

**Issue by mikechen66** [PacktPublishing/Mastering-Computer-Vision-with-TensorFlow-2.0#6]
It has the ResourceExhaustedError on Nvidia RTX 2070 Super 

ResourceExhaustedError: OOM when allocating tensor with shape[173056,4096]

---------------------------------------------------------------------------
ResourceExhaustedError                    Traceback (most recent call last)
<ipython-input-8-5e78d7c42b85> in <module>
     17     Flatten(),
     18     Dense(4096, activation='relu'),
---> 19     Dense(3)
     20 ])

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py in _method_wrapper(self, *args, **kwargs)
    454     self._self_setattr_tracking = False  # pylint: disable=protected-access
    455     try:
--> 456       result = method(self, *args, **kwargs)
    457     finally:
    458       self._self_setattr_tracking = previous_value  # pylint: disable=protected-access

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/sequential.py in __init__(self, layers, name)
    127       tf_utils.assert_no_legacy_layers(layers)
    128       for layer in layers:
--> 129         self.add(layer)
    130 
    131   @property

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py in _method_wrapper(self, *args, **kwargs)
    454     self._self_setattr_tracking = False  # pylint: disable=protected-access
    455     try:
--> 456       result = method(self, *args, **kwargs)
    457     finally:
    458       self._self_setattr_tracking = previous_value  # pylint: disable=protected-access

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/sequential.py in add(self, layer)
    211       # If the model is being built continuously on top of an input layer:
    212       # refresh its output.
--> 213       output_tensor = layer(self.outputs[0])
    214       if len(nest.flatten(output_tensor)) != 1:
    215         raise ValueError(SINGLE_LAYER_OUTPUT_ERROR_MSG)

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, *args, **kwargs)
    895           # Build layer if applicable (if the `build` method has been
    896           # overridden).
--> 897           self._maybe_build(inputs)
    898           cast_inputs = self._maybe_cast_inputs(inputs)
    899 

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py in _maybe_build(self, inputs)
   2414         # operations.
   2415         with tf_utils.maybe_init_scope(self):
-> 2416           self.build(input_shapes)  # pylint:disable=not-callable
   2417       # We must set also ensure that the layer is marked as built, and the build
   2418       # shape is stored since user defined build functions may not be calling

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py in build(self, input_shape)
   1163         constraint=self.kernel_constraint,
   1164         dtype=self.dtype,
-> 1165         trainable=True)
   1166     if self.use_bias:
   1167       self.bias = self.add_weight(

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py in add_weight(self, name, shape, dtype, initializer, regularizer, trainable, constraint, partitioner, use_resource, synchronization, aggregation, **kwargs)
    575         synchronization=synchronization,
    576         aggregation=aggregation,
--> 577         caching_device=caching_device)
    578     if regularizer is not None:
    579       # TODO(fchollet): in the future, this should be handled at the

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py in _add_variable_with_custom_getter(self, name, shape, dtype, initializer, getter, overwrite, **kwargs_for_getter)
    741         dtype=dtype,
    742         initializer=initializer,
--> 743         **kwargs_for_getter)
    744 
    745     # If we set an initializer and the variable processed it, tracking will not

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer_utils.py in make_variable(name, shape, dtype, initializer, trainable, caching_device, validate_shape, constraint, use_resource, collections, synchronization, aggregation, partitioner)
    139       synchronization=synchronization,
    140       aggregation=aggregation,
--> 141       shape=variable_shape if variable_shape else None)
    142 
    143 

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/ops/variables.py in __call__(cls, *args, **kwargs)
    257   def __call__(cls, *args, **kwargs):
    258     if cls is VariableV1:
--> 259       return cls._variable_v1_call(*args, **kwargs)
    260     elif cls is Variable:
    261       return cls._variable_v2_call(*args, **kwargs)

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/ops/variables.py in _variable_v1_call(cls, initial_value, trainable, collections, validate_shape, caching_device, name, variable_def, dtype, expected_shape, import_scope, constraint, use_resource, synchronization, aggregation, shape)
    218         synchronization=synchronization,
    219         aggregation=aggregation,
--> 220         shape=shape)
    221 
    222   def _variable_v2_call(cls,

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/ops/variables.py in <lambda>(**kwargs)
    196                         shape=None):
    197     """Call on Variable class. Useful to force the signature."""
--> 198     previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
    199     for _, getter in ops.get_default_graph()._variable_creator_stack:  # pylint: disable=protected-access
    200       previous_getter = _make_getter(getter, previous_getter)

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py in default_variable_creator(next_creator, **kwargs)
   2596         synchronization=synchronization,
   2597         aggregation=aggregation,
-> 2598         shape=shape)
   2599   else:
   2600     return variables.RefVariable(

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/ops/variables.py in __call__(cls, *args, **kwargs)
    261       return cls._variable_v2_call(*args, **kwargs)
    262     else:
--> 263       return super(VariableMetaclass, cls).__call__(*args, **kwargs)
    264 
    265 

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py in __init__(self, initial_value, trainable, collections, validate_shape, caching_device, name, dtype, variable_def, import_scope, constraint, distribute_strategy, synchronization, aggregation, shape)
   1432           aggregation=aggregation,
   1433           shape=shape,
-> 1434           distribute_strategy=distribute_strategy)
   1435 
   1436   def _init_from_args(self,

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py in _init_from_args(self, initial_value, trainable, collections, caching_device, name, dtype, constraint, synchronization, aggregation, distribute_strategy, shape)
   1565           with ops.name_scope("Initializer"), device_context_manager(None):
   1566             initial_value = ops.convert_to_tensor(
-> 1567                 initial_value() if init_from_fn else initial_value,
   1568                 name="initial_value", dtype=dtype)
   1569           if shape is not None:

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer_utils.py in <lambda>()
    119         (type(init_ops.Initializer), type(init_ops_v2.Initializer))):
    120       initializer = initializer()
--> 121     init_val = lambda: initializer(shape, dtype=dtype)
    122     variable_dtype = dtype.base_dtype
    123   if use_resource is None:

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/ops/init_ops_v2.py in __call__(self, shape, dtype)
    556     else:
    557       limit = math.sqrt(3.0 * scale)
--> 558       return self._random_generator.random_uniform(shape, -limit, limit, dtype)
    559 
    560   def get_config(self):

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/ops/init_ops_v2.py in random_uniform(self, shape, minval, maxval, dtype)
   1066       op = random_ops.random_uniform
   1067     return op(
-> 1068         shape=shape, minval=minval, maxval=maxval, dtype=dtype, seed=self.seed)
   1069 
   1070   def truncated_normal(self, shape, mean, stddev, dtype):

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/ops/random_ops.py in random_uniform(shape, minval, maxval, dtype, seed, name)
    299           result = math_ops.multiply(result, maxval)
    300       else:
--> 301         result = math_ops.add(result * (maxval - minval), minval, name=name)
    302     # TODO(b/132092188): C++ shape inference inside functional ops does not
    303     # cross FuncGraph boundaries since that information is only available in

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py in binary_op_wrapper(x, y)
    982     with ops.name_scope(None, op_name, [x, y]) as name:
    983       if isinstance(x, ops.Tensor) and isinstance(y, ops.Tensor):
--> 984         return func(x, y, name=name)
    985       elif not isinstance(y, sparse_tensor.SparseTensor):
    986         try:

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py in _mul_dispatch(x, y, name)
   1281   is_tensor_y = isinstance(y, ops.Tensor)
   1282   if is_tensor_y:
-> 1283     return gen_math_ops.mul(x, y, name=name)
   1284   else:
   1285     assert isinstance(y, sparse_tensor.SparseTensor)  # Case: Dense * Sparse.

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/ops/gen_math_ops.py in mul(x, y, name)
   6087         pass  # Add nodes to the TensorFlow graph.
   6088     except _core._NotOkStatusException as e:
-> 6089       _ops.raise_from_not_ok_status(e, name)
   6090   # Add nodes to the TensorFlow graph.
   6091   _, _, _op, _outputs = _op_def_library._apply_op_helper(

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py in raise_from_not_ok_status(e, name)
   6651   message = e.message + (" name: " + name if name is not None else "")
   6652   # pylint: disable=protected-access
-> 6653   six.raise_from(core._status_to_exception(e.code, message), None)
   6654   # pylint: enable=protected-access
   6655 

~/miniconda3/lib/python3.7/site-packages/six.py in raise_from(value, from_value)

ResourceExhaustedError: OOM when allocating tensor with shape[173056,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:Mul]

**Comment by mikechen66** [comment]
I solve the issue. It is as same as the script of Chapter_6_Transferlearning_VisualSearch.ipynb. However, users need to add the lines of code related to the two new added classes. 

**1.  Modify the line of code**

change the original line of code 
`class_list = ["bed", "chair", "sofa"]`
to the following code
`class_list = ["bed", "chair", "sofa", "swivelchair", "table"]`

**2. Add the lines of code related to the two added classes** 

Please note the commence before the new added code. 

```
train_bed_dir = os.path.join(train_dir, 'bed') 
train_chair_dir = os.path.join(train_dir, 'chair')  
train_sofa_dir = os.path.join(train_dir, 'sofa') 
train_swivelchair_dir = os.path.join(train_dir, 'swivelchair') 
train_table_dir = os.path.join(train_dir, 'table') 

val_bed_dir = os.path.join(val_dir, 'bed')  
val_chair_dir = os.path.join(val_dir, 'chair')  
val_sofa_dir = os.path.join(val_dir, 'sofa')  
# Add the swivelchair
val_swivelchair_dir = os.path.join(val_dir, 'swivelchair')  
# Add the table 
val_table_dir = os.path.join(val_dir, 'table')  

num_bed_train = len(os.listdir(train_bed_dir))
num_chair_train = len(os.listdir(train_chair_dir))
num_sofa_train = len(os.listdir(train_sofa_dir))
# Add the swivelchair
num_swivelchair_train = len(os.listdir(train_swivelchair_dir))
# Add the table 
num_table_train = len(os.listdir(train_table_dir))

num_bed_val = len(os.listdir(val_bed_dir))
num_chair_val = len(os.listdir(val_chair_dir))
num_sofa_val = len(os.listdir(val_sofa_dir))
# Add the swivelchair
num_swivelchair_val = len(os.listdir(val_swivelchair_dir))
# Add the table 
num_table_val = len(os.listdir(val_table_dir))

# Add the number of both swivelchair and table
num_train_images = num_bed_train + num_chair_train + num_sofa_train + num_swivelchair_train + num_table_train
# Add the number of both swivelchair and table
num_val_images = num_bed_val + num_chair_val + num_sofa_val + num_swivelchair_val + num_table_val
print(num_train_images, num_val_images)
```
**3. Excuete the code in either  VGG16 or custom_mode**

The VGG script runs well without the OOM(Out of Memory) error.  Please remember executing the script of  VGG16(or custom_mode) respectively. 

Cheers!

**Comment by mikechen66** [comment]
There is a trick related to the script of custom_mode. The dense (Dense) layer has the parameters of 268439552. In contrast, the total parameter size－274,567,557. It sometimes get the OOM(Out-of-Memory) error. 

I think there is a huge imbalance between the size of the convolutional layer and the dense layer in script of custom_mode. 

Besides, the Alex-like custom_mode hide the input size of 150 x 150. It only shows the changed size of 140 x140. It would make us confused. 
conv2d (Conv2D)              (None, 140, 140, 96)      34944     

Therefore, I change the custom_mode with the total size of 73,736,133 as follows. 

Downloads the furniture datasets in the book
https://www.kaggle.com/akkithetechie/furniture-detector

```
# BUILD A CUSTOM MODEL-SKIP THIS STEP IF YOU USE VGG16. FOR CUSTOM MODEL USE THIS STEP AND SKIP NEXT TWO STEPS
model = Sequential([
    Conv2D(64, 3, padding='same', activation='relu', 
           input_shape=(img_height, img_width ,3)),
    Conv2D(64, 3, padding='same', activation='relu'), 
    MaxPooling2D(),
    Dropout(0.2),
    Conv2D(128, 3, padding='same', activation='relu'),
    Conv2D(128, 3, padding='same', activation='relu'),
    MaxPooling2D(),
    Conv2D(128, 3, padding='same', activation='relu'),
    Conv2D(256, 3, padding='same', activation='relu'),
    Conv2D(512, 3, padding='same', activation='relu'),
    MaxPooling2D(),
    Dropout(0.2),
    Conv2D(1024, 3, padding='same', activation='relu'),
    MaxPooling2D(),
    Dropout(0.2),
    MaxPooling2D(),
    Flatten(),
    Dense(4096, activation='relu'),
    Dense(5)
])
```

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
conv2d (Conv2D)              (None, 150, 150, 64)      1792      
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 150, 150, 64)      36928     
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 75, 75, 64)        0         
_________________________________________________________________
dropout (Dropout)            (None, 75, 75, 64)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 75, 75, 128)       73856     
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 75, 75, 128)       147584    
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 37, 37, 128)       0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 37, 37, 128)       147584    
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 37, 37, 256)       295168    
_________________________________________________________________
conv2d_6 (Conv2D)            (None, 37, 37, 512)       1180160   
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 18, 18, 512)       0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 18, 18, 512)       0         
_________________________________________________________________
conv2d_7 (Conv2D)            (None, 18, 18, 1024)      4719616   
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 9, 9, 1024)        0         
_________________________________________________________________
dropout_2 (Dropout)          (None, 9, 9, 1024)        0         
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 4, 4, 1024)        0         
_________________________________________________________________
flatten (Flatten)            (None, 16384)             0         
_________________________________________________________________
dense (Dense)                (None, 4096)              67112960  
_________________________________________________________________
dense_1 (Dense)              (None, 5)                 20485     
=================================================================
Total params: 73,736,133
Trainable params: 73,736,133
Non-trainable params: 0

That will be quite smaller than the original total size of the custom_mode.

**Comment by gaurav-packt** [comment]
Thanks for the update.
