### ISSUE TITLE
Chapter_6_Transferlearning_VisualSearch: InvalidArgumentError:  logits and labels must be broadcastable: logits_size=[10,3] labels_size=[10,5]

### ISSUE THREAD

**Issue by mikechen66** [PacktPublishing/Mastering-Computer-Vision-with-TensorFlow-2.0#7]
Chapter6_Transferlearning_VisualSearch

InvalidArgumentError:  logits and labels must be broadcastable: logits_size=[10,3] labels_size=[10,5]
	 [[node categorical_crossentropy/softmax_cross_entropy_with_logits (defined at <ipython-input-7-204dec9d4a80>:7) ]] [Op:__inference_train_function_17797]

Detailed error messages listed as follows. 

#---------------------------------------------------------------------------------------------------------------
adam = Adam(lr=0.00001)

final_model.compile(adam, loss='categorical_crossentropy', metrics=['accuracy'])

​

history = final_model.fit_generator(train_generator, epochs=NUM_EPOCHS, workers=0, 

                                       steps_per_epoch=num_train_images // batchsize, 

                                       shuffle=True, validation_data=val_generator,

        validation_steps=num_val_images // batchsize)

​

​

WARNING:tensorflow:From <ipython-input-7-204dec9d4a80>:7: Model.fit_generator (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
Please use Model.fit, which supports generators.
Epoch 1/5

---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-7-204dec9d4a80> in <module>
      5                                        steps_per_epoch=num_train_images // batchsize,
      6                                        shuffle=True, validation_data=val_generator,
----> 7         validation_steps=num_val_images // batchsize)
      8 

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py in new_func(*args, **kwargs)
    322               'in a future version' if date is None else ('after %s' % date),
    323               instructions)
--> 324       return func(*args, **kwargs)
    325     return tf_decorator.make_decorator(
    326         func, new_func, 'deprecated',

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1477         use_multiprocessing=use_multiprocessing,
   1478         shuffle=shuffle,
-> 1479         initial_epoch=initial_epoch)
   1480 
   1481   @deprecation.deprecated(

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
     64   def _method_wrapper(self, *args, **kwargs):
     65     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
---> 66       return method(self, *args, **kwargs)
     67 
     68     # Running inside `run_distribute_coordinator` already.

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
    846                 batch_size=batch_size):
    847               callbacks.on_train_batch_begin(step)
--> 848               tmp_logs = train_function(iterator)
    849               # Catch OutOfRangeError for Datasets of unknown size.
    850               # This blocks until the batch has finished executing.

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    578         xla_context.Exit()
    579     else:
--> 580       result = self._call(*args, **kwds)
    581 
    582     if tracing_count == self._get_tracing_count():

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    642         # Lifting succeeded, so variables are initialized and we can run the
    643         # stateless function.
--> 644         return self._stateless_fn(*args, **kwds)
    645     else:
    646       canon_args, canon_kwds = \

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py in __call__(self, *args, **kwargs)
   2418     with self._lock:
   2419       graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
-> 2420     return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
   2421 
   2422   @property

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py in _filtered_call(self, args, kwargs)
   1663          if isinstance(t, (ops.Tensor,
   1664                            resource_variable_ops.BaseResourceVariable))),
-> 1665         self.captured_inputs)
   1666 
   1667   def _call_flat(self, args, captured_inputs, cancellation_manager=None):

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1744       # No tape is watching; skip to running the function.
   1745       return self._build_call_outputs(self._inference_function.call(
-> 1746           ctx, args, cancellation_manager=cancellation_manager))
   1747     forward_backward = self._select_forward_and_backward_functions(
   1748         args,

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py in call(self, ctx, args, cancellation_manager)
    596               inputs=args,
    597               attrs=attrs,
--> 598               ctx=ctx)
    599         else:
    600           outputs = execute.execute_with_cancellation(

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

InvalidArgumentError:  logits and labels must be broadcastable: logits_size=[10,3] labels_size=[10,5]
	 [[node categorical_crossentropy/softmax_cross_entropy_with_logits (defined at <ipython-input-7-204dec9d4a80>:7) ]] [Op:__inference_train_function_17797]

Function call stack:
train_function

**Comment by KrishkarPackt** [comment]
At the time of writing the book, I get warning only,  So I gave updated code in 
Chapter6_Transferlearning_VisualSearch_tfdata_tensor as follows - please replace history with this

history = final_model.fit(train_ds,epochs=NUM_EPOCHS,steps_per_epoch=num_train_images // batchsize,callbacks=[checkpoint_callback],validation_data=val_ds, validation_steps=num_val_images // batchsize)

**Comment by mikechen66** [comment]
I use the RTX 2070 Super with 8 GB GPU Memory. 

It shows the following error messages after adopting your update line of code. 

**1. train_ds is not defined** 

**2. checkpoint_callback is not defined**

**3. InvalidArgumentError repeated** 

_InvalidArgumentError:  logits and labels must be broadcastable: logits_size=[10,3] labels_size=[10,5]
	 [[node categorical_crossentropy/softmax_cross_entropy_with_logits (defined at <ipython-input-10-e35650ec7c82>:17) ]] [Op:__inference_train_function_17828]
Function call stack:
train_function_

**4. Same error after adding some lines of code**

I do not know why it happened.  It generated the same error while I updated the following code. 

```
# Compile the model 
adam = Adam(lr=0.00001)
final_model.compile(adam, 
                    loss='categorical_crossentropy', 
                    metrics=['accuracy'])

# Start Tensorboard --logdir logs/fit
log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir)
callback_list = [tensorboard_callback]

# Train the model 
history = final_model.fit(train_generator,
                          epochs=NUM_EPOCHS,
                          steps_per_epoch=num_train_images // batchsize,
                          # -callbacks=[checkpoint_callback],
                          validation_data=val_generator, 
                          validation_steps=num_val_images // batchsize,
                          callbacks=callback_list)

# Show the graph
%tensorboard --logdir logs/fit
```

**Comment by KrishkarPackt** [comment]
You have to modify the code to give directory name correctly. Here is what you have to do, I verified it and it runs.

Please replace
history = final_model.fit_generator(train_generator, epochs=NUM_EPOCHS, workers=0, 
                                       steps_per_epoch=num_train_images // batchsize, 
                                       shuffle=True, validation_data=val_generator,
        validation_steps=num_val_images // batchsize)


with

history = final_model.fit(train_generator,epochs=NUM_EPOCHS,steps_per_epoch=num_train_images // batchsize,validation_data=val_generator, validation_steps=num_val_images // batchsize)


Epoch 1/5
90/90 [==============================] - 39s 428ms/step - loss: 0.9894 - accuracy: 0.5078 - val_loss: 0.8156 - val_accuracy: 0.7700
Epoch 2/5
90/90 [==============================] - 43s 478ms/step - loss: 0.7486 - accuracy: 0.7300 - val_loss: 0.6863 - val_accuracy: 0.8100
Epoch 3/5
90/90 [==============================] - 43s 473ms/step - loss: 0.6196 - accuracy: 0.7989 - val_loss: 0.5605 - val_accuracy: 0.8300
Epoch 4/5
90/90 [==============================] - 42s 466ms/step - loss: 0.5072 - accuracy: 0.8467 - val_loss: 0.4045 - val_accuracy: 0.8600
Epoch 5/5
90/90 [==============================] - 41s 460ms/step - loss: 0.4474 - accuracy: 0.8533 - val_loss: 0.3764 - val_accuracy: 0.8900

**Comment by mikechen66** [comment]
I know where is wrong and change it to a success. Please see the following comments. 

Because the designated downloading file in the book have 5 classes including bed, chair, sofa, swivelchair and table, but the original script has only 3 classes including bed, chair and sofa. So it is a mismatch and generates an error--logits_size=[10,3] labels_size=[10,5]

Downloads the furniture datasets in the book 
https://www.kaggle.com/akkithetechie/furniture-detector

The original line of code in your script 
`class_list = ["bed", "chair", "sofa"]`

The new line of code updated 
`class_list = ["bed", "chair", "sofa", "swivelchair", "table"]`

After updating the line of code, I can run the updated script successfully. 

Epoch 1/30
64/64 [==============================] - 72s 1s/step - loss: 1.4812 - accuracy: 0.3700 - val_loss: 1.2208 - val_accuracy: 0.7175
Epoch 2/30
64/64 [==============================] - 68s 1s/step - loss: 1.1815 - accuracy: 0.6034 - val_loss: 0.9633 - val_accuracy: 0.7725
Epoch 3/30
64/64 [==============================] - 69s 1s/step - loss: 0.9547 - accuracy: 0.7034 - val_loss: 0.7430 - val_accuracy: 0.8000
......
Epoch 28/30
64/64 [==============================] - 67s 1s/step - loss: 0.3026 - accuracy: 0.8906 - val_loss: 0.3114 - val_accuracy: 0.8975
Epoch 29/30
64/64 [==============================] - 67s 1s/step - loss: 0.3120 - accuracy: 0.8853 - val_loss: 0.3427 - val_accuracy: 0.8675
Epoch 30/30
64/64 [==============================] - 67s 1s/step - loss: 0.2986 - accuracy: 0.8909 - val_loss: 0.2891 - val_accuracy: 0.9075

Thanks.
