### ISSUE TITLE
Chapter6_Transferlearning_VisualSearch_tfdata_tensor -FileNotFoundError: [Errno 2] No such file or directory: 

### ISSUE THREAD

**Issue by mikechen66** [PacktPublishing/Mastering-Computer-Vision-with-TensorFlow-2.0#8]
No testdata, need to split the test data from the train dataset

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-22-992c970b89f6> in <module>
     14 maxcosine =0
     15 i=0
---> 16 for filename in os.listdir(path):
     17     image_train = os.path.join(path, filename)
     18     i +=1

FileNotFoundError: [Errno 2] No such file or directory: './Krishnendu_CV2TF/Chapter06/furniture_images/img/test/sofa'

**Comment by KrishkarPackt** [comment]
make sure your images are there in your path
if y_classes == [0]:
    path = 'furniture_images/test/bed'
elif y_classes == [1]:
    path = 'furniture_images/test/chair'
else:
    path = 'furniture_images/test/sofa'

**Comment by KrishkarPackt** [comment]
Also please refer to Github section read me 
https://github.com/PacktPublishing/Mastering-Computer-Vision-with-TensorFlow-2.0/blob/master/README.md
 You can review additional description screen video for each code block to solve file missing issue in your case.  This will give you idea where to place your file.

**Comment by mikechen66** [comment]
Thanks for your reply. I use the library of spli-folders to split the original dataset into train, val and test sets. And then it can run successfully. It is a great experience. 

Downloads the furniture datasets
https://www.kaggle.com/akkithetechie/furniture-detector

```
# split_folders.py 

# pip install split-folders
import splitfolders  

# The path to the directory where the original dataset was uncompressed
input_folder = 'home/user/datasets/kaggle/furniture_pictures'
# The directory where we will store our smaller dataset
output_folder = 'home/user/Documents/Krishnendu_CV2TF/Chapter06/furniture_pictures'

splitfolders.ratio(input_folder, output_folder, seed=1337, ratio=(.8, .1, .1), group_prefix=None) 
```

Cheers!
