### ISSUE TITLE
Chapter9_TF_Accelerometer_activity : FileNotFoundError: [Errno 2] File sample.csv does not exist: 'sample.csv'

### ISSUE THREAD

**Issue by mikechen66** [PacktPublishing/Mastering-Computer-Vision-with-TensorFlow-2.0#9]
There is no weblink for the necessary file of sample.csv. 

 FileNotFoundError: [Errno 2] File sample.csv does not exist: 'sample.csv'

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-3-e002327884ed> in <module>
----> 1 dataframe = read_data('sample.csv')
      2 dataframe.head()

<ipython-input-2-94af701556d5> in read_data(file_path)
      4     df = pd.read_csv(file_path,
      5                      header=None,
----> 6                      names=column_names)
      7     df['z-axis'].replace(regex=True,
      8       inplace=True,

~/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
    674         )
    675 
--> 676         return _read(filepath_or_buffer, kwds)
    677 
    678     parser_f.__name__ = name

~/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py in _read(filepath_or_buffer, kwds)
    446 
    447     # Create the parser.
--> 448     parser = TextFileReader(fp_or_buf, **kwds)
    449 
    450     if chunksize or iterator:

~/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py in __init__(self, f, engine, **kwds)
    878             self.options["has_index_names"] = kwds["has_index_names"]
    879 
--> 880         self._make_engine(self.engine)
    881 
    882     def close(self):

~/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py in _make_engine(self, engine)
   1112     def _make_engine(self, engine="c"):
   1113         if engine == "c":
-> 1114             self._engine = CParserWrapper(self.f, **self.options)
   1115         else:
   1116             if engine == "python":

~/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py in __init__(self, src, **kwds)
   1889         kwds["usecols"] = self.usecols
   1890 
-> 1891         self._reader = parsers.TextReader(src, **kwds)
   1892         self.unnamed_cols = self._reader.unnamed_cols
   1893 

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.__cinit__()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._setup_parser_source()

FileNotFoundError: [Errno 2] File sample.csv does not exist: 'sample.csv'

**Comment by KrishkarPackt** [comment]
File needs to be in your local path
dataframe = read_data('sample.csv') 
dataframe.head()

**Comment by KrishkarPackt** [comment]
Also please refer to Github section read me 
https://github.com/PacktPublishing/Mastering-Computer-Vision-with-TensorFlow-2.0/blob/master/README.md
 You can review additional description screen video for each code block to solve file missing issue in your case.  This will give you idea where to place your file.

**Comment by mikechen66** [comment]
Dear KrishkarPackt:

I know that I need a local path as descripted as follows. 

**Give a specific path**

`dataframe = read_data('home/user/Documents/Krishnendu_CV2TF/Chapter09/sample.csv') `

But the problem is that there is neither weblink of sample.csv in your book nor in the related github 
folder. Please see the following words in your book. 

**Recognizing actions based on an accelerometer**
......
Two files can be found at the previous link: Chapter9_TF_Accelerometer_activity.ipynb and 
sample.csv. _Download both files and put them under the same folder._

The sample.csv file is a sample CSV file containing accelerometer (x,y,z) data for six different actions: 
Jogging (0), Walking (1), Upstairs (2), Downstairs (3), Sitting (4), and Standing (5), with each actions 
containing 5,000 data points. In your actual scenario, these data values can be different based on
placement location and the type of accelerometer being used. It is better to take the training data with
the same accelerometer for inference to avoid inference errors.

Look forward to getting a further help from you. 

Thanks.

**Comment by KrishkarPackt** [comment]
added sample.csv

**Comment by mikechen66** [comment]
Thank a lot. I run it and it works fine after downloading the sample.csv from the website today.
